apiVersion: v1
kind: Service
metadata:
  name: my-kart-product-service
  namespace: my-kart-product
spec:
  type: NodePort
  selector:
    app: my-kart-product
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083  # You can change or omit this
