apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-kart-user-logs-pv
  labels:
    type: local
    app: my-kart-user
spec:
  storageClassName: standard
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/my-kart-user-logs"