apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kart-user-deployment
  namespace: my-kart-user
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: my-kart-user
          image: docker.io/harshdesai695/user-tomcat:2.0
          ports:
            - containerPort: 8081
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: my-kart-user-config
                  key: MONGODB_URI
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/local/logs
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: my-kart-user-logs-pvc
